services:
  library-maintainer:
    build:
      context: ../library-maintainer
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    environment:
      - LANGUAGE_FILTER=eng,en  # Support both eng and en language codes
      - DOWNLOAD_ALL=true
      - UPDATE_SCHEDULE=0 2 * * *  # Run at 2 AM daily
      - MAX_CONCURRENT_DOWNLOADS=3
      - VERIFY_DOWNLOADS=true
      - LOG_LEVEL=DEBUG  # Enhanced logging level
      - DEBUG_CONTENT_MATCHING=true  # Add detailed content matching logs
      - PRINT_CONTENT_LIST=true  # Print full content list being processed
      - CONTENT_PATTERN=.*_en.*|.*english.*|.*_eng_.*|.*_en_all.*  # Enhanced pattern to match more English content variants
      - SCAN_SUBDIRS=true  # Scan all subdirectories
      - MEMORY_LIMIT=4G  # Increase memory limit for larger datasets
      - DOWNLOAD_TIMEOUT=3600  # Increase download timeout to 1 hour
      - BASE_URL=https://download.kiwix.org/zim/  # Explicitly set the base URL
    volumes:
      - ./kiwix:/data:rw
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - kiwix_network
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os.access('/data/library.xml', os.R_OK) or exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve:latest
    ports:
      - "3119:8080"
    volumes:
      - ./kiwix:/data:ro
    user: "1000:1000"
    command: --library /data/library.xml --verbose
    depends_on:
      library-maintainer:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - kiwix_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/catalog"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  kiwix_data:
    name: apocacache_kiwix_data_eng

networks:
  kiwix_network:
    name: apocacache_network_eng 