version: '3.8'

services:
  library-maintainer:
    build:
      context: ../library-maintainer
      dockerfile: Dockerfile
    environment:
      - LANGUAGE_FILTER=eng
      - DOWNLOAD_ALL=true
      - UPDATE_SCHEDULE=0 2 * * *  # Run at 2 AM daily
      - KIWIX_SERVER_URL=http://kiwix-serve:8080
    volumes:
      - ./kiwix:/data
    restart: unless-stopped
    depends_on:
      kiwix-serve:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve:latest
    ports:
      - "8080:8080"
    volumes:
      - ./kiwix:/data:ro
    command: --library /data/library.xml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/catalog"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  kiwix_data:
    driver: local

networks:
  default:
    driver: bridge 