services:
  library-maintainer:
    build:
      context: ../library-maintainer
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    environment:
      - LANGUAGE_FILTER=en
      - DOWNLOAD_ALL=true
      - UPDATE_SCHEDULE=0 2 * * *  # Run at 2 AM daily
      - MAX_CONCURRENT_DOWNLOADS=3
      - VERIFY_DOWNLOADS=true
      - LOG_LEVEL=INFO
    volumes:
      - ./kiwix:/data:rw
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - kiwix_network
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os.access('/data/library.xml', os.R_OK) or exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve:latest
    ports:
      - "3119:8080"
    volumes:
      - ./kiwix:/data:ro
    user: "1000:1000"
    command: --library /data/library.xml
    depends_on:
      library-maintainer:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - kiwix_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/catalog"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  kiwix_data:
    name: apocacache_kiwix_data_eng

networks:
  kiwix_network:
    name: apocacache_network_eng 